### ISSUE TITLE
split log by size, add time tag to archive file SIGSEVF if no sequence number

### ISSUE THREAD

**Issue by DigiTester** [HardySimpson/zlog#74]
I've been trying to rotate and timestamp log files, and unfortunately both zlog and zlog-chk-conf SIGSEV when reading the following line:

*.ERROR  "aa.log", 10MB ~ "aa-%d(%Y%m%d-%H%M%S).log"
#*.ERROR  "aa.log", 10MB ~ logs/aa-%d(%Y%m%d-%H%M%S).#2s.log

The commented out line is fine. Adding the "#2s" is the key, it appears that your code does something horrid if there's no sequence number in the filename.

Even if the sequence number is required I think a SIGSEVF is a pretty brutal way to indicate an error :)

**Comment by HardySimpson** [comment]
fixed in master, the SIGSEVF comes from strchr(NULL, 's'); 
The output now is

 ./zlog-chk-conf ../test/test_conf.conf
04-27 17:41:14 ERROR (20177:rule.c:799) archive_path must contain #r or #s
04-27 17:41:14 ERROR (20177:conf.c:487) zlog_rule_new fail [*.ERROR "aa.log", 10MB ~ "aa-%d(%Y%m%d-%H%M%S).log"]
04-27 17:41:14 ERROR (20177:conf.c:314) parse configure file[../test/test_conf.conf]line_no[31] fail
04-27 17:41:14 ERROR (20177:conf.c:315) line[*.ERROR "aa.log", 10MB ~ "aa-%d(%Y%m%d-%H%M%S).log"]
04-27 17:41:14 ERROR (20177:conf.c:160) zlog_conf_build_with_file fail
04-27 17:41:14 ERROR (20177:zlog.c:93) zlog_conf_new[../test/test_conf.conf] fail
04-27 17:41:14 ERROR (20177:zlog.c:135) zlog_init_inner[../test/test_conf.conf] fail
04-27 17:41:14 ERROR (20177:zlog.c:150) ------zlog_init fail end------

---[../test/test_conf.conf] syntax error, see error message above

**Comment by DigiTester** [comment]
Thanks for the quick fix.
